// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC57W-mHBuqa0XSp3wKiOU2KF_i7uQN3KY',
    appId: '1:424049997628:web:01d83ac2d676e3db6b1039',
    messagingSenderId: '424049997628',
    projectId: 'push-notifications-ecdd4',
    authDomain: 'push-notifications-ecdd4.firebaseapp.com',
    storageBucket: 'push-notifications-ecdd4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxVjDoNTfeJwDW1iM6orJcf-8WwTfhwp0',
    appId: '1:424049997628:android:c8fa2c654b7259a46b1039',
    messagingSenderId: '424049997628',
    projectId: 'push-notifications-ecdd4',
    storageBucket: 'push-notifications-ecdd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrmLgW8S-Is_T92W-c2w3AEIuMRIF2P6E',
    appId: '1:424049997628:ios:b2b5a87dd305bdf96b1039',
    messagingSenderId: '424049997628',
    projectId: 'push-notifications-ecdd4',
    storageBucket: 'push-notifications-ecdd4.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrmLgW8S-Is_T92W-c2w3AEIuMRIF2P6E',
    appId: '1:424049997628:ios:b2b5a87dd305bdf96b1039',
    messagingSenderId: '424049997628',
    projectId: 'push-notifications-ecdd4',
    storageBucket: 'push-notifications-ecdd4.firebasestorage.app',
    iosBundleId: 'com.example.pushNotifications1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC57W-mHBuqa0XSp3wKiOU2KF_i7uQN3KY',
    appId: '1:424049997628:web:9b5e1327022696ea6b1039',
    messagingSenderId: '424049997628',
    projectId: 'push-notifications-ecdd4',
    authDomain: 'push-notifications-ecdd4.firebaseapp.com',
    storageBucket: 'push-notifications-ecdd4.firebasestorage.app',
  );
}
